from public.ecr.aws/sam/build-python3.8

RUN mkdir -p /opt/package

COPY executables /opt/package

RUN chmod +x /opt/package/*

ENV PATH="/opt/package/bin:${PATH}"
ENV LD_LIBRARY_PATH="/opt/package/lib:${LD_LIBRARY_PATH}"




COPY data/ /opt/package/data


RUN ls /opt/package/data

RUN chmod +x /opt/package/data

RUN encoderTest /opt/package/data/test.wav

RUN ls /opt/package/data



